name: Terrania-GS
author: Adrodoc55
version: 0.9.4
main: de.adrodoc55.minecraft.plugins.terrania.gs.TerraniaGsPlugin

depend: [WorldGuard]

commands:
    gs:
       description: Grundstueck Befehle
       usage: /gs

permissions:
    terrania:
        gs:
            commands:
                gs:
                    create: op
                    delete: op
                    setprice: op
                    addmember: op
                    removemember: op
                    info: op
                    list: true
                    update: op
                    save: op
